### ISSUE TITLE
Kernel 5.8 in Fedora 32: Cannot set fan speed error

### ISSUE THREAD

**Issue by brianpepino** [linux-on-mac/mbpfan#223] opened 2020-09-07 04:52 UTC
Hi Guys,

I am running kernel 5.8 using Fedora 32 on a Macbook Pro Retina 13'inch mid-2014 model and I encounter "cannot set fan speed" error. 

Any additional details you require from me to troubleshoot this error? or is this a kernel bug?

For the time being, I am now using kernel 5.7 which has no issues.

Thanks.

**Comment by gaul** [comment] 2020-09-07 05:30
Duplicate of #221.

**Closed by gaul** 2020-09-07 05:30 UTC
